baseurl = "https://domain.example" # Controls base URL sitewide
languageCode = "en-US" # Controls site language
title = "theyknow" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating

# Controls default theme and theme components
theme = [
  "fractal-forest", # OBSD
  "after-dark" # AGPL-3.0-or-later
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = false # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[params]
  description = "" # Suggested, controls default description meta
  author = "theyknow" # Optional, controls author name display on posts
  hide_author = false # Optional, set true to hide author name on posts
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://images.alphacoders.com/712/thumb-1920-712781.jpg"
  ] # Suggested, controls default Open Graph images

[params.layout.footer]
  hidden = false # Optional, set true to hide footer

[params.modules.fractal_forest]
  enabled = true # Optional, set false to disable module
  decoders = ["bpgdec8a"] # Optional, 8-bit javascript decoder with animation

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post"

[[menu.main]]
  name = "Tools"
  weight = 3
  identifier = "tools"
  url = "/tools"

[[menu.main]]
  name = "Twitter"
  weight = 4
  identifier = "twitter"
  url = "https://twitter.com/victor_theyknow"

[[menu.main]]
  name = "GitHub"
  weight = 5
  identifier = "github"
  url = "https://github.com/Prune2000"

[[menu.main]]
  name = "@"
  weight = 6
  identifier = "email"
  url = "mailto:c.victor.p@protonmail.com"

[params.hackcss]
  palette = "solarized-dark"

